GET https://competition-project.herokuapp.com/participants

###
GET https://competition-project.herokuapp.com/participants/1

###
POST https://competition-project.herokuapp.com/participants
Content-Type: application/json

{
  "id": 0,
  "name": "AmpaipornAA",
  "surname": "Jitmaingong",
  "country": "Thailand",
  "city": "Surin",
  "age": 27,
  "gender": "F",
  "competence": "Creativity and Design",
  "competenceName": "Floristics",
  "urlImage": "https://asiapoisk.com/uploads/cache/people/jW6zwc-465x600.jpg"
}

###
POST https://competition-project.herokuapp.com/participants
Content-Type: application/json

{
  "id": 1,
  "name": "AmpaipornAA",
  "surname": "Jitmaingong",
  "country": "Thailand",
  "city": "Surin",
  "age": 25,
  "gender": "F",
  "competence": "Creativity and Design",
  "competenceName": "Floristics",
  "urlImage": "https://asiapoisk.com/uploads/cache/people/jW6zwc-465x600.jpg"
}

###
DELETE https://competition-project.herokuapp.com/participants/12

###
GET https://competition-project.herokuapp.com/participants/search?minAge=18&maxAge=30&competenceName=Floristics



###
GET https://competition-project.herokuapp.com/participants/competition/points
###
GET https://competition-project.herokuapp.com/participants/competition/points/10
###
GET https://competition-project.herokuapp.com/participants/competition/points/maxPointsOne




###
GET http://localhost:8080/participants

###
GET http://localhost:8080/participants/part

###
GET http://localhost:8080/points

###
GET http://localhost:8080/points/max

###
GET http://localhost:8080/participants/1


###

POST http://localhost:8080/participants
Content-Type: application/json

{
  "id": 0,
  "name": "AmpaipornAA",
  "surname": "Jitmaingong",
  "country": "Thailand",
  "city": "Surin",
  "age": 27,
  "gender": "F",
  "competence": "Creativity and Design",
  "competenceName": "Floristics",
  "urlImage": "https://asiapoisk.com/uploads/cache/people/jW6zwc-465x600.jpg"
}


###
// это будет по другому
http://localhost:8080/participants/11/remove

###
DELETE http://localhost:8080/participants/12

###
GET http://localhost:8080/participants/points

###
GET http://localhost:8080/participants/points/maxPointsOne

###
GET http://localhost:8080/participants/points/10

###
GET http://localhost:8080/competition/points/1

###

GET http://localhost:8080/participants/search?minAge=18&maxAge=30&competenceName=Floristics

###
GET http://localhost:8080/teams/1

###
GET http://localhost:8080/teams/1/paymentForOnePerson?participantsNumber=5


